# Generated by Django 4.2.5 on 2023-11-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_qty_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty_available',
        ),
    ]
