# Generated by Django 4.2.4 on 2024-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='billing name', max_length=50),
        ),
    ]
