# Generated by Django 4.2.5 on 2023-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address2_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_status',
            field=models.BooleanField(default=False),
        ),
    ]
