# Generated by Django 4.2.4 on 2024-01-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAdmin',
        ),
    ]
